### ISSUE TITLE
the question of running project with Spanish

### ISSUE THREAD

**Issue by aduotang** [hasanhuz/SpanEmo#9] opened 2022-07-09 06:54 UTC
Hi! I am trying to reproduce the Spanish part, but there have a ValueError: 'anticip' is not in list. I have already download bert-base-spanish-wwm-uncased.

Could you please provide the suggests for me?

Thanks in advance.

**Comment by hasanhuz** [comment] 2022-07-09 21:28
Hi there, thank you for your interest in our work. It seems to me the error is caused by the Bert-base encoder. I suggest to check the dictionary of the model if it contains the word "anticip", if not, then you must provide a replacement word so that Bert-base can generate its embedding.
Hope this helps,
Hassan

**Comment by hasanhuz** [comment] 2022-07-15 00:21
Since no further questions have been asked, I will close the issue. However, feel free to reopen it in case you have any one.

**Closed by hasanhuz** 2022-07-15 00:21 UTC
